# generated by datamodel-codegen:
#   filename:  api2.yaml
#   timestamp: 2024-02-10T14:20:35+00:00

from __future__ import annotations

from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, EmailStr, Field


class Drone(BaseModel):
    id: Optional[UUID] = Field(None, description='Unique identifier for the drone')
    name: str = Field(..., description='Name of the drone')
    model: Optional[str] = Field(None, description='Model of the drone')
    user_id: Optional[UUID] = Field(
        None, description='ID of the user who owns the drone'
    )


class User(BaseModel):
    id: Optional[UUID] = Field(None, description='Unique identifier for the user')
    name: str = Field(..., description='Name of the user')
    email: Optional[EmailStr] = Field(None, description='Email address of the user')
    role: Optional[str] = Field(
        None, description='Role of the user (e.g., admin, operator)'
    )


class Waypoint(BaseModel):
    latitude: Optional[float] = Field(
        None, description='Latitude coordinate of the waypoint'
    )
    longitude: Optional[float] = Field(
        None, description='Longitude coordinate of the waypoint'
    )


class FlightPlan(BaseModel):
    id: Optional[UUID] = Field(
        None, description='Unique identifier for the flight plan'
    )
    name: Optional[str] = Field(None, description='Name of the flight plan')
    description: Optional[str] = Field(
        None, description='Description of the flight plan'
    )
    waypoints: Optional[List[Waypoint]] = Field(
        None, description='List of waypoints for the flight plan'
    )
